# csi-sanity build container
FROM golang:1.16 as builder-csi-sanity
WORKDIR /go/src/github.com/kubernetes-csi/
# csi-sanity versions: https://github.com/kubernetes-csi/csi-test/releases
ARG CSI_SANITY_VERSION_TAG
ENV CSI_SANITY_VERSION_TAG=$CSI_SANITY_VERSION_TAG
RUN git clone https://github.com/kubernetes-csi/csi-test.git &&\
    cd csi-test &&\
    git checkout -b ${CSI_SANITY_VERSION_TAG} ${CSI_SANITY_VERSION_TAG} &&\
    cd cmd/csi-sanity &&\
    make linux_amd64_dist &&\
    cp ./csi-sanity /csi-sanity


# driver build container
FROM golang:1.16 as builder-driver
WORKDIR /go/src/github.com/Nexenta/nexentastor-csi-driver-block/
COPY . ./
RUN make build &&\
    cp ./bin/nexentastor-csi-driver-block /nexentastor-csi-driver-block


# run driver and csi-sanity tests
FROM alpine:3.10
WORKDIR /
# driver UNIX socket
ENV SOCK="unix:///csi.sock"
# install dependencies
RUN apk update || true &&  \
    apk add coreutils util-linux blkid \
    e2fsprogs bash kmod curl jq ca-certificates


# copy csi-sanity from build container
COPY --from=builder-csi-sanity /csi-sanity /
# copy driver from build container
RUN mkdir /nexentastor-csi-driver-block
COPY --from=builder-driver /nexentastor-csi-driver-block /nexentastor-csi-driver-block/
RUN mkdir /lib64 &&\
    ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2
ADD chroot-host-wrapper.sh /nexentastor-csi-driver-block
RUN chmod 777 /nexentastor-csi-driver-block/chroot-host-wrapper.sh
RUN    ln -s /nexentastor-csi-driver-block/chroot-host-wrapper.sh /nexentastor-csi-driver-block/blkid \
    && ln -s /nexentastor-csi-driver-block/chroot-host-wrapper.sh /nexentastor-csi-driver-block/ln \
    && ln -s /nexentastor-csi-driver-block/chroot-host-wrapper.sh /nexentastor-csi-driver-block/iscsiadm \
    && ln -s /nexentastor-csi-driver-block/chroot-host-wrapper.sh /nexentastor-csi-driver-block/resize2fs \
    && ln -s /nexentastor-csi-driver-block/chroot-host-wrapper.sh /nexentastor-csi-driver-block/blockdev \
    && ln -s /nexentastor-csi-driver-block/chroot-host-wrapper.sh /nexentastor-csi-driver-block/e2fsck \
    && ln -s /nexentastor-csi-driver-block/chroot-host-wrapper.sh /nexentastor-csi-driver-block/findmnt \
    && ln -s /nexentastor-csi-driver-block/chroot-host-wrapper.sh /nexentastor-csi-driver-block/lsscsi \
    && ln -s /nexentastor-csi-driver-block/chroot-host-wrapper.sh /nexentastor-csi-driver-block/mkfs.ext3 \
    && ln -s /nexentastor-csi-driver-block/chroot-host-wrapper.sh /nexentastor-csi-driver-block/mkfs.ext4 \
    && ln -s /nexentastor-csi-driver-block/chroot-host-wrapper.sh /nexentastor-csi-driver-block/mkfs.xfs \
    && ln -s /nexentastor-csi-driver-block/chroot-host-wrapper.sh /nexentastor-csi-driver-block/multipath \
    && ln -s /nexentastor-csi-driver-block/chroot-host-wrapper.sh /nexentastor-csi-driver-block/rm \
    && ln -s /nexentastor-csi-driver-block/chroot-host-wrapper.sh /nexentastor-csi-driver-block/multipathd 
ENV PATH="/nexentastor-csi-driver-block/:${PATH}"
# copy driver config file
COPY ./tests/csi-sanity/driver-config-csi-sanity.yaml /config/driver-config-csi-sanity.yaml
# create mount direactory for tests
# driver run script
RUN echo '/nexentastor-csi-driver-block/nexentastor-csi-driver-block --config-dir=/config --endpoint=${SOCK} --nodeid=local &' > /run-driver &&\
    chmod +x /run-driver
# details: https://stackoverflow.com/questions/34729748/installed-go-binary-not-found-in-path-on-alpine-linux-docker
# versions
RUN /csi-sanity -csi.version &&\
    /nexentastor-csi-driver-block/nexentastor-csi-driver-block --version
# other csi-sanity options: --ginkgo.v -ginkgo.noColor
#TODO remove "--ginkgo.skip" option after fixing volume paginatin by token:
ENTRYPOINT ["/bin/sh", "-c", "/run-driver && /csi-sanity --csi.endpoint=${SOCK} --csi.createpathcmdtimeout=180 --csi.removepathcmdtimeout=180 --ginkgo.skip 'pagination should detect volumes added between pages and accept tokens when the last volume from a page is deleted'"]
#ENTRYPOINT ["/bin/sh", "-c", "/run-driver && /csi-sanity --csi.endpoint=${SOCK} --csi.createpathcmdtimeout=180 --csi.removepathcmdtimeout=180]