---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nexentastor-csi-snapshotter-role
  labels:
    app.kubernetes.io/name: nexentastor-block-csi-controller
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents/status"]
    verbs: ["update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nexentastor-csi-snapshotter-binding
  labels:
    app.kubernetes.io/name: nexentastor-block-csi-controller
subjects:
  - kind: ServiceAccount
    name: nexentastor-block-csi-controller-service-account
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: nexentastor-csi-snapshotter-role
  apiGroup: rbac.authorization.k8s.io