# Nginx pod with dynamic storage creation using NexentaStor Block CSI driver
#
# $ kubectl apply -f examples/kubernetes/nginx-dynamic-volume.yaml
#
# --------------------------------------
# NexentaStor CSI Driver - Storage Class
# --------------------------------------

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nexentastor-block-csi-driver-sc-nginx-dynamic
provisioner: nexentastor-block-csi-driver.nexenta.com
allowVolumeExpansion: true
---

# ------------------------------------------------
# NexentaStor CSI Driver - Persistent Volume Claim
# ------------------------------------------------

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexentastor-block-csi-driver-pvc-nginx-dynamic
spec:
  storageClassName: nexentastor-block-csi-driver-sc-nginx-dynamic
  accessModes:
    - ReadWriteOnce
    # - ReadWriteMany
  # volumeMode: Block
  resources:
    requests:
      storage: 1Gi
---

# # ------------------------------------------------
# # NexentaStor CSI Driver - Persistent Volume Claim
# # ------------------------------------------------

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: nexentastor-block-csi-driver-pvc-nginx-dynamic-2
# spec:
#   storageClassName: nexentastor-block-csi-driver-sc-nginx-dynamic
#   accessModes:
#     # - ReadWriteMany
#     - ReadWriteOnce
#   # volumeMode: Block
#   resources:
#     requests:
#       storage: 2Gi
# ---

# # ------------------------------------------------
# # NexentaStor CSI Driver - Persistent Volume Claim
# # ------------------------------------------------

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: nexentastor-block-csi-driver-pvc-nginx-dynamic-3
# spec:
#   storageClassName: nexentastor-block-csi-driver-sc-nginx-dynamic
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 3Gi
# ---

# ---------
# Nginx deployment
# ---------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-dynamic
  labels:
    app.kubernetes.io/name: nginx-deployment-dynamic
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-deployment-dynamic
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-deployment-dynamic
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - image: nginx
          imagePullPolicy: IfNotPresent
          name: nginx
          command: ["bash"]
          args: ["-c", "while true; do echo $(date) >> /mountedDisk/datefile; sleep 0.1; done"] #--hdd-noclean
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /mountedDisk
              name: nexentastor-block-csi-driver-data
            # - mountPath: /mountedDisk-2
            #   name: nexentastor-block-csi-driver-data-2
            # - mountPath: /mountedDisk-3
            #   name: nexentastor-block-csi-driver-data-3
      volumes:
        - name: nexentastor-block-csi-driver-data
          persistentVolumeClaim:
            claimName: nexentastor-block-csi-driver-pvc-nginx-dynamic
            readOnly: false
        # - name: nexentastor-block-csi-driver-data-2
        #   persistentVolumeClaim:
        #     claimName: nexentastor-block-csi-driver-pvc-nginx-dynamic-2
        #     readOnly: false
        # - name: nexentastor-block-csi-driver-data-3
        #   persistentVolumeClaim:
        #     claimName: nexentastor-block-csi-driver-pvc-nginx-dynamic-3
        #     readOnly: false
