apiVersion: v1
kind: Pod
metadata:
  name: nginx-dynamic-volume2
spec:
  containers:
    - image: nginx
      imagePullPolicy: IfNotPresent
      name: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      # volumeDevices:
      volumeMounts:
        - mountPath: /mntDisk
        # - devicePath: /dev/sdd
          name: nexentastor-block-csi-driver-data
  volumes:
    - name: nexentastor-block-csi-driver-data
      persistentVolumeClaim:
        claimName: nexentastor-block-csi-driver-pvc-nginx-dynamic
        readOnly: false
---
