# Create a new snapshot class
#
# !!! Make sure to run nginx-persistent-volume.yaml before running this example
#
# $ kubectl apply -f examples/kubernetes/snapshot-class.yaml
#

apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: nexentastor-block-csi-snapshot-class
driver: nexentastor-block-csi-driver.nexenta.com
deletionPolicy: Delete
# parameters:
#   csi.storage.k8s.io/snapshotter-secret-name: demo-secret
#   csi.storage.k8s.io/snapshotter-secret-namespace: default
