# Create a new snapshot class
#
# !!! Make sure to run nginx-persistent-volume.yaml before running this example
#
# $ kubectl apply -f examples/kubernetes/snapshot-class.yaml
#

apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshotClass
metadata:
  name: nexentastor-block-csi-snapshot-class
snapshotter: nexentastor-block-csi-driver.nexenta.com
# parameters:
#   csiSnapshotterSecretName: csi-secret
#   csiSnapshotterSecretNamespace: csi-namespace
#   TODO add "dataset" parameter support
